kind: pipeline
type: docker
name: release

steps:
  - name: 编译分支源码
    commands:
      - ls -la

trigger:
  branch:
    include:
      - master
      - fix*
      - feat*
  event:
    include:
      - push
